language: python
python: "3.6"
sudo: required
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
install:
  - pip install tox coveralls
script: tox
after_success:
  if [ "$TOXENV" == "py27" ]; then coveralls; fi
